const movieActionTypes = {
  FETCH_MOVIES: 'FETCH_MOVIES',
  FETCH_MOVIES_SUCCESS: 'FETCH_MOVIES_SUCCESS',
  FETCH_MOVIES_START: 'FETCH_MOVIES_START',
  FETCH_MOVIES_FINISH: 'FETCH_MOVIES_FINISH',
  FETCH_MOVIES_FAIL: 'FETCH_MOVIES_FAIL',
  FETCH_MOVIE_SUCCESS: 'FETCH_MOVIE_SUCCESS'
};

export default movieActionTypes;
