const userActionTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SIGN_UP_FAIL: 'SIGN_UP_FAIL',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_IN_FAIL: 'SIGN_IN_FAIL',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SET_USER_REVIEWS: 'SET_USER_REVIEWS'
};

export default userActionTypes;
